spring:
  datasource:
    url: jdbc:mysql://172.18.0.1:3306/notes?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.18.0.1
    port: 6379
    database: 1
    password: qwerty