mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://39.97.166.233:3306/notes?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.97.166.233
    port: 6379
    database: 1
