# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: Run maven script
      uses: xlui/action-maven-cli/jdk11@master
      id: test
      with:
        lifecycle: 'package'
